/**
 * Provider API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppointmentDTO { 
    id?: number;
    slotId?: number;
    bookedByUserId?: string;
    isProxyBooking?: boolean;
    patientName?: string;
    patientPhone?: string;
    status?: AppointmentDTO.StatusEnum;
    checkedInAt?: string;
    cancelledAt?: string;
    createdAt?: string;
    updatedAt?: string;
}
export namespace AppointmentDTO {
    export const StatusEnum = {
        PENDING: 'PENDING',
        SCHEDULED: 'SCHEDULED',
        CANCELLED: 'CANCELLED',
        LATE_CANCEL: 'LATE_CANCEL',
        ATTENDED: 'ATTENDED',
        NO_SHOW: 'NO_SHOW',
        COMPLETED: 'COMPLETED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


