/**
 * Provider API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvailabilitySlotDTO { 
    id?: number;
    doctorId?: string;
    hospitalId?: number;
    startTime?: string;
    endTime?: string;
    readonly doctorName?: string;
    createdAt?: string;
}

