/**
 * Provider API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DoctorRegistrationRequest { 
    email: string;
    firstName: string;
    lastName: string;
    medicalLicenseNumber: string;
    specialization?: string;
    password: string;
}

