/**
 * Provider API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HospitalInfoDTO { 
    id?: number;
    name?: string;
    licenseNumber?: string;
    status?: string;
    region?: string;
    woredaCity?: string;
    adminId?: string;
}

