/**
 * Provider API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HospitalRegistrationRequest { 
    name: string;
    licenseNumber: string;
    adminEmail: string;
    adminFirstName: string;
    adminLastName: string;
    password: string;
    region: string;
    woredaCity?: string;
}

