/**
 * Provider API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HospitalStaffDTO { 
    userId?: string;
    name?: string;
    role?: string;
    isActive?: boolean;
    approvedAt?: string;
    joinedAt?: string;
}

