/**
 * Provider API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HospitalUpdateRequest { 
    name?: string;
    region?: string;
    woredaCity?: string;
}

