/**
 * Provider API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InviteInfoDTO { 
    hospitalId?: number;
    hospitalName?: string;
    status?: string;
    expiresAt?: string;
}

