/**
 * Provider API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleChangeRequest { 
    role: RoleChangeRequest.RoleEnum;
}
export namespace RoleChangeRequest {
    export const RoleEnum = {
        DOCTOR: 'DOCTOR',
        SCHEDULER: 'SCHEDULER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


